services:
  phonebook:
    build: .
    ports:
      - "4567:4567"
    volumes:
      - .:/app
      - phonebook-data:/app/contacts
    environment:
      - RACK_ENV=development
    command: ruby app.rb -o 0.0.0.0
    stdin_open: true
    tty: true

volumes:
  phonebook-data:
    driver: local
